spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:mariadb://localhost:3306/webflix
    username: root
    password: rWfZmagGgFbdus4E0PsJREfC
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

adminuser:
  username: admin
  password: admin